- hosts: kube_node
  gather_facts: false
  tasks:
    - name: Copy calicoctl
      copy:
        src: "/usr/local/bin/calicoctl"
        dest: /usr/bin/calicoctl
        mode: "0755"

- hosts:
    - kube_client

  roles:
    - kube-calico
