- name: Prepare k8s install dirs
  file:
    name: "{{ YAML_GEN_DIR }}"
    state: directory

- name: Create kube-flannel.yml
  template:
    src: kube-flannel.yml.j2
    dest: "{{ YAML_GEN_DIR }}/kube-flannel.yml"

- name: deploy kube-flannel
  debug:
    msg: "  kubectl apply -f {{ YAML_GEN_DIR }}/kube-flannel.yml  "
