---
- name: show hosts information
  debug:
    msg: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ ansible_distribution_release }}"

- include: centos.yml
  when: 'ansible_distribution in ["CentOS","RedHat"]'

- include: ubuntu.yml
  when: 'ansible_distribution in ["Ubuntu","Debian"]'

- name: enable chronyd.service
  systemd:
    name: chronyd.service
    enabled: true
    state: started

- name: Set TimeZone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
    backup: yes
  with_items:
    - swap
    - none
  register: DISABLE_SWAP_RESULT

- name: disable swap
  shell: "swapoff -a"
  changed_when: DISABLE_SWAP_RESULT.changed
